services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./certs/mongo:/etc/ssl/mongo
    ports:
      - "27017:27017"
    command: >
      mongod --tlsMode requireTLS
             --tlsCertificateKeyFile /etc/ssl/mongo/server.pem
             --tlsCAFile /etc/ssl/mongo/ca.crt
  game-server:
    build:
      context: ./code
      dockerfile: ./game-server-v2/Dockerfile
    volumes:
      - ./code/beastly-brawl-showdown/imports/simulator:/app/simulator
      - ./certs/server:/etc/ssl/server
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: "mongodb://mongo:27017/test?tls=true&tlsCertificateKeyFile=/etc/ssl/server/client.pem&tlsCAFile=/etc/ssl/server/ca.crt"

  meteor-app:
    build:
      context: ./code/beastly-brawl-showdown
    volumes:
      - ./certs/server:/etc/ssl/server
    depends_on:
      - game-server
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL="mongodb://mongo:27017/beastly?tls=true&tlsCertificateKeyFile=/etc/ssl/server/client.pem&tlsCAFile=/etc/ssl/server/ca.crt"
      - ROOT_URL="http://localhost"
      - ROOT_URL=http://localhost
      - PORT=3000

volumes:
  mongo-data:
