version: "3.8"
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  game-server:
    build:
      context: ./code
      dockerfile: ./game-server-v2/Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  meteor-app:
    build:
      context: ./code/beastly-brawl-showdown
    depends_on:
      - game-server
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/beastly
      - ROOT_URL=http://localhost
      - PORT=3000

volumes:
  mongo-data:
